Tim Produk, dibantu oleh Tim Marketing, saat ini sedang meluncurkan dua produk/jasa terbaru, dan salah satunya merupakan jasa yang digunakan untuk menunjang penjualan produk yang sudah ada, produk PINJAMAN DANA MULTIGUNA. Oleh karena itu, mereka sedang membutuhkan Tim Data untuk melakukan beberapa analisa yang sangat mendesak untuk membantu mereka meningkatkan peluang cross-selling produk/jasa terbaru mereka untuk tahap awal (A/B testing). Sayangnya, saat ini tidak ada BI yang tersedia di Business Intelligence Center. Oleh karena itu, seorang Data Scientist di tim CRM Analytics dan anda sebagai Data
Scientist Intern akan ditugaskan menyelesaikan permasalahan tersebut. Ini adalah peluang anda untuk menunjukkan kemampuan anda dan juga sebagai jalan untuk anda membiasakan diri dengan apa yang Data Scientist di Home Credit kerjakan.

In [19]:
import pandas as pd

# Gantilah 'nama_file.csv' dengan nama file yang sesuai
data_pelanggan = pd.read_csv('/content/drive/MyDrive/Portofolio/Data Analyst/Marketing_Campaign_Data_A-21492758-f47a-4913-971e-68c9a721311a.csv')
data_pelanggan.head()

,Unnamed: 0,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,NAME_EDUCATION_TYPE,NAME_HOUSING_TYPE,REGION_POPULATION_RELATIVE,REGION_RATING_CLIENT_W_CITY,APPL_DATETIME,DATE_BIRTH
0,58785,0,Cash loans,F,Y,Y,157500.0,225000.0,11781.0,225000.0,Secondary / secondary special,House / apartment,0.014520,2,2016-06-11 17:28:54,17-07-1959
1,166116,0,Cash loans,F,N,Y,180000.0,508495.5,21672.0,454500.0,Secondary / secondary special,House / apartment,0.031329,2,2015-05-22 08:42:03,23-06-1951
2,170111,0,Cash loans,F,Y,Y,360000.0,639396.0,47934.0,571500.0,Incomplete higher,House / apartment,0.032561,1,2016-11-26 20:54:07,07-06-1979
3,184247,0,Cash loans,F,N,Y,162000.0,254700.0,14751.0,225000.0,Higher education,House / apartment,0.010147,2,2017-02-20 09:22:06,20-07-1958
4,75886,0,Cash loans,M,Y,Y,225000.0,787131.0,42066.0,679500.0,Higher education,House / apartment,0.025164,2,2017-02-28 09:38:45,05-08-1985

In [20]:
# Ganti kolom 'Unnamed: 0' dengan 'SK_ID_CURR'
data_pelanggan.rename(columns={'Unnamed: 0': 'SK_ID_CURR'}, inplace=True)

data_pelanggan.head()

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,NAME_EDUCATION_TYPE,NAME_HOUSING_TYPE,REGION_POPULATION_RELATIVE,REGION_RATING_CLIENT_W_CITY,APPL_DATETIME,DATE_BIRTH
0,58785,0,Cash loans,F,Y,Y,157500.0,225000.0,11781.0,225000.0,Secondary / secondary special,House / apartment,0.014520,2,2016-06-11 17:28:54,17-07-1959
1,166116,0,Cash loans,F,N,Y,180000.0,508495.5,21672.0,454500.0,Secondary / secondary special,House / apartment,0.031329,2,2015-05-22 08:42:03,23-06-1951
2,170111,0,Cash loans,F,Y,Y,360000.0,639396.0,47934.0,571500.0,Incomplete higher,House / apartment,0.032561,1,2016-11-26 20:54:07,07-06-1979
3,184247,0,Cash loans,F,N,Y,162000.0,254700.0,14751.0,225000.0,Higher education,House / apartment,0.010147,2,2017-02-20 09:22:06,20-07-1958
4,75886,0,Cash loans,M,Y,Y,225000.0,787131.0,42066.0,679500.0,Higher education,House / apartment,0.025164,2,2017-02-28 09:38:45,05-08-1985

In [3]:
data_pelanggan.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30722 entries, 0 to 30721
Data columns (total 16 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   SK_ID_CURR                   30722 non-null  int64
 1   TARGET                       30722 non-null  int64
 2   NAME_CONTRACT_TYPE           30722 non-null  object
 3   CODE_GENDER                  30722 non-null  object
 4   FLAG_OWN_CAR                 30722 non-null  object
 5   FLAG_OWN_REALTY              30722 non-null  object
 6   AMT_INCOME_TOTAL             30722 non-null  float64
 7   AMT_CREDIT                   30722 non-null  float64
 8   AMT_ANNUITY                  30722 non-null  float64
 9   AMT_GOODS_PRICE              30722 non-null  float64
 10  NAME_EDUCATION_TYPE          30722 non-null  object
 11  NAME_HOUSING_TYPE            30722 non-null  object
 12  REGION_POPULATION_RELATIVE   30722 non-null  float64
 13  REGION_RATING_CLIENT_W_CITY  30722 non-null  int64
 14  APPL_DATETIME                30722 non-null  object
 15  DATE_BIRTH                   30722 non-null  object
dtypes: float64(5), int64(3), object(8)
memory usage: 3.8+ MB

- "Late Ten" : Age<20
- "Twenty" : 20 <= Age<30
- "Thirty" : 30 <= Age<40
- "Fourty" : 40 <= Age<50
- "Fifty" : 50 <= Age<60
- "Above_Sixty" : 60 <= Age
Sebagai catatan, tim marketing hanya membutuhkan data pelanggan yang tidak memiliki kesulitan
pembayaran (karena ini terkait dengan kemampuan mereka dalam membeli produk) dan tinggal di wilayah
yang diberi rating 3 (REGION_RATING_CLIENT_W_CITY) serta melakukan transaksi pada tanggal 1 Januari
2017 - 31 Desember 2018.

In [22]:
data_pelanggan['DATE_BIRTH'] = pd.to_datetime(data_pelanggan['DATE_BIRTH'], format='%d-%m-%Y')
data_pelanggan['APPL_DATETIME'] = pd.to_datetime(data_pelanggan['APPL_DATETIME'], format='%Y-%m-%d')

In [32]:
filtered_data = data_pelanggan.loc[
    (data_pelanggan['TARGET'] == 0) &
    (data_pelanggan['REGION_RATING_CLIENT_W_CITY'] == 3) &
    (data_pelanggan['APPL_DATETIME'] >= '2017-01-01') &
    (data_pelanggan['APPL_DATETIME'] <= '2018-12-31')
].copy()
filtered_data.head()

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,NAME_EDUCATION_TYPE,NAME_HOUSING_TYPE,REGION_POPULATION_RELATIVE,REGION_RATING_CLIENT_W_CITY,APPL_DATETIME,DATE_BIRTH
21,95421,0,Cash loans,F,N,Y,135000.0,648000.0,33214.5,648000.0,Secondary / secondary special,House / apartment,0.018209,3,2017-04-22 14:25:01,1949-12-13
26,180539,0,Cash loans,F,N,Y,225000.0,545040.0,25537.5,450000.0,Secondary / secondary special,House / apartment,0.010500,3,2018-05-26 00:05:43,1993-07-28
84,133649,0,Cash loans,M,N,Y,121500.0,302206.5,16524.0,229500.0,Secondary / secondary special,Rented apartment,0.020713,3,2017-03-04 19:28:13,1960-04-04
102,171795,0,Cash loans,F,Y,N,135000.0,1042164.0,58324.5,931500.0,Incomplete higher,Office apartment,0.008068,3,2018-09-15 04:40:56,1981-02-12
103,132002,0,Cash loans,F,N,Y,90000.0,868500.0,36927.0,868500.0,Secondary / secondary special,House / apartment,0.002134,3,2017-07-10 03:28:47,1995-12-15

In [33]:
# Fungsi untuk mengelompokkan umur
def categorize_age(age):
    if age < 20:
        return 'Late_Ten'
    elif age < 30:
        return 'Twenty'
    elif age < 40:
        return 'Thirty'
    elif age < 50:
        return 'Fourty'
    elif age < 60:
        return 'Fifty'
    else:
        return 'Above_Sixty'

In [36]:
# Terapkan fungsi kategorisasi umur pada data
filtered_data['Age_Group'] = (filtered_data['APPL_DATETIME'] - filtered_data['DATE_BIRTH']).dt.days // 365
filtered_data['Age_Group'] = filtered_data['Age_Group'].apply(categorize_age)

# Urutkan hasil sesuai dengan urutan umur
result = filtered_data['Age_Group'].value_counts().reindex(['Late_Ten', 'Twenty', 'Thirty', 'Fourty', 'Fifty', 'Above_Sixty'])

# Tampilkan hasil
print(result)

Late_Ten         NaN
Twenty         364.0
Thirty         305.0
Fourty         198.0
Fifty          582.0
Above_Sixty    488.0
Name: Age_Group, dtype: float64

#SOAL NO 2
Sebagai Data Scientist di Home Credit Indonesia, kita dapat ditempatkan di berbagai tim yang berbeda seperti tim Smart Data
Analytics, tim Customer Relationship Management Analytics, dan tim Scoring Analytics. Karenanya, kita diharapkan untuk memiliki
kemampuan untuk menangani dan memproses data secara end-to-end. Oleh karena itu, kemampuan dalam membuat clean data dari
raw data yang sudah ada, termasuk memahami Entity Relationship Diagram merupakan hal dasar yang harus anda kuasai.
Untuk memahami kegiatan sehari-hari Data Scientist di Home Credit Indonesia, tugas pertama anda sebagai intern adalah
mengimplementasikan kemampuan dalam membuat clean data baru untuk dilakukan analisis terkait distribusi pelanggan setelahnya.

In [45]:
import pandas as pd

# Gantilah 'nama_file.csv' dengan nama file yang sesuai
data1 = pd.read_csv('/content/drive/MyDrive/Portofolio/Data Analyst/hci_previous_application_0-9cc2b69c-f469-4d66-bfdf-48b23f2c006a.csv')
# # Ganti kolom 'Unnamed: 0' dengan 'SK_ID_CURR'
# df.rename(columns={'Unnamed: 0': 'SK_ID_CURR'}, inplace=True)
data1.head()

,SK_ID_PREV,SK_ID_CURR,NAME_CONTRACT_TYPE,AMT_APPLICATION,NAME_CONTRACT_STATUS
0,1038818,100002,Consumer loans,179055.0,Approved
1,1810518,100003,Cash loans,900000.0,Approved
2,2636178,100003,Consumer loans,337500.0,Approved
3,2396755,100003,Consumer loans,68809.5,Approved
4,1564014,100004,Consumer loans,24282.0,Approved

In [44]:
# Gantilah 'nama_file.csv' dengan nama file yang sesuai
data2 = pd.read_csv('/content/drive/MyDrive/Portofolio/Data Analyst/hci_application_0-2f6a4257-a1e4-4f59-88a4-d425c8ae1eaf.csv')
# # Ganti kolom 'Unnamed: 0' dengan 'SK_ID_CURR'
# df.rename(columns={'Unnamed: 0': 'SK_ID_CURR'}, inplace=True)
data2.head()

   SK_ID_CURR  TARGET CODE_GENDER FLAG_OWN_CAR FLAG_OWN_REALTY  CNT_CHILDREN
0      100002       1           F            N               Y             0
1      100003       0           F            N               N             0
2      100004       0           F            Y               Y             0
3      100006       0           F            N               Y             0
4      100007       0           F            N               Y             0

In [47]:
# Menggabungkan data berdasarkan kolom SK_ID_CURR
merged_data = pd.merge(data2, data1, on='SK_ID_CURR', how='inner')
merged_data.head()

,SK_ID_CURR,TARGET,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,SK_ID_PREV,NAME_CONTRACT_TYPE,AMT_APPLICATION,NAME_CONTRACT_STATUS
0,100002,1,F,N,Y,0,1038818,Consumer loans,179055.0,Approved
1,100003,0,F,N,N,0,1810518,Cash loans,900000.0,Approved
2,100003,0,F,N,N,0,2636178,Consumer loans,337500.0,Approved
3,100003,0,F,N,N,0,2396755,Consumer loans,68809.5,Approved
4,100004,0,F,Y,Y,0,1564014,Consumer loans,24282.0,Approved

In [48]:
# Menyaring data sesuai kondisi yang diberikan
filtered_data = merged_data[
    (merged_data['CODE_GENDER'] == 'F') &
    (merged_data['CNT_CHILDREN'] > 0) &
    (merged_data['TARGET'] == 0) &
    (merged_data['NAME_CONTRACT_STATUS'] == 'Approved')
]
filtered_data.head()

,SK_ID_CURR,TARGET,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,SK_ID_PREV,NAME_CONTRACT_TYPE,AMT_APPLICATION,NAME_CONTRACT_STATUS
25,100009,0,F,Y,Y,1,1413109,Consumer loans,98239.5,Approved
26,100009,0,F,Y,Y,1,2227125,Consumer loans,46876.5,Approved
27,100009,0,F,Y,Y,1,2421381,Consumer loans,47160.0,Approved
28,100009,0,F,Y,Y,1,2007057,Consumer loans,40455.0,Approved
29,100009,0,F,Y,Y,1,2797899,Consumer loans,95841.0,Approved

In [49]:
# Kondisi 1: Banyaknya pengajuan kredit yang disetujui dari pelanggan wanita yang memiliki anak dan tidak memiliki masalah/kesulitan dalam proses pembayaran (TARGET = 0)
result_condition_1 = len(filtered_data)

# Kondisi 2: Tipe kontrak (NAME_CONTRACT_TYPE) yang memiliki pengajuan kredit yang paling banyak disetujui dari pelanggan wanita yang memiliki anak dan tidak memiliki masalah/kesulitan dalam proses pembayaran (TARGET = 0)
most_approved_contract_type = filtered_data['NAME_CONTRACT_TYPE'].value_counts().idxmax()

# Kondisi 3: Banyaknya pengajuan kredit yang disetujui dari pelanggan wanita yang memiliki anak dan tidak memiliki masalah/kesulitan dalam proses pembayaran (TARGET = 0) untuk tipe kontrak Consumer Loans
result_condition_3 = len(filtered_data[filtered_data['NAME_CONTRACT_TYPE'] == 'Consumer loans'])

# Kondisi 4: Tipe kontrak (NAME_CONTRACT_TYPE) yang memiliki pengajuan kredit yang paling banyak disetujui kedua dari pelanggan wanita yang memiliki anak dan tidak memiliki masalah/kesulitan dalam proses pembayaran (TARGET = 0)
second_most_approved_contract_type = filtered_data['NAME_CONTRACT_TYPE'].value_counts().index[1]

# Kondisi 5: Banyaknya pengajuan kredit yang disetujui dari pelanggan wanita yang memiliki anak dan tidak memiliki masalah/kesulitan dalam proses pembayaran (TARGET = 0) untuk tipe kontrak Cash Loans
result_condition_5 = len(filtered_data[filtered_data['NAME_CONTRACT_TYPE'] == 'Cash loans'])

# Menampilkan hasil
print(f"Banyaknya pengajuan kredit yang disetujui: {result_condition_1}")
print(f"Tipe kontrak paling banyak disetujui: {most_approved_contract_type}")
print(f"Banyaknya pengajuan kredit Consumer Loans yang disetujui: {result_condition_3}")
print(f"Tipe kontrak kedua paling banyak disetujui: {second_most_approved_contract_type}")
print(f"Banyaknya pengajuan kredit Cash Loans yang disetujui: {result_condition_5}")

Banyaknya pengajuan kredit yang disetujui: 15637
Tipe kontrak paling banyak disetujui: Consumer loans
Banyaknya pengajuan kredit Consumer Loans yang disetujui: 10585
Tipe kontrak kedua paling banyak disetujui: Cash loans
Banyaknya pengajuan kredit Cash Loans yang disetujui: 3646